/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'laddu' : IDL.Null,
  'chutneyPowder' : IDL.Null,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'shelfLife' : IDL.Text,
  'category' : Category,
  'usageSuggestions' : IDL.Vec(IDL.Text),
  'nutritionalBenefits' : IDL.Vec(IDL.Text),
  'ingredients' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'initSampleProducts' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'laddu' : IDL.Null,
    'chutneyPowder' : IDL.Null,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'shelfLife' : IDL.Text,
    'category' : Category,
    'usageSuggestions' : IDL.Vec(IDL.Text),
    'nutritionalBenefits' : IDL.Vec(IDL.Text),
    'ingredients' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'initSampleProducts' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };