/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'laddu' : null } |
  { 'chutneyPowder' : null };
export interface Product {
  'name' : string,
  'description' : string,
  'shelfLife' : string,
  'category' : Category,
  'usageSuggestions' : Array<string>,
  'nutritionalBenefits' : Array<string>,
  'ingredients' : Array<string>,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'initSampleProducts' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];